### ISSUE TITLE
email not send when I push "send email" button at sales->order page in admin area

### ISSUE THREAD

**Issue by bank32** [aschroder/Magento-SMTP-Pro-Email-Extension#45] opened 2014-07-10 11:44 UTC
Dear Aschroder

I want to resend email to my customer but I have a problem email not send when I push "send email" button at order page in admin area, how can I solved it ?

Thank you very much.

**Comment by aschroder** [comment] 2015-01-04 23:14
Are you sure it sends emails without smtp pro installed? Can you test and
check that. Otherwise you could also put debug statements into the
controller action and check what it is doing before sending (or attempting
to send) the email.

**Comment by bialy7** [comment] 2015-01-05 18:04
It's look like button "send email" using different class for customers who is not logged in. 
Yours plugin work fine in other cases (comments, new order on frontend etc) but not in case when I push button "Send email"

**Comment by marticos** [comment] 2015-02-26 17:20
This problem is very annoying.

**Comment by KLVTZ** [comment] 2015-02-26 18:29
@aschroder @bialy7 @marticos I'll have some free time this weekend to replicate the issue. I have a few client apps that use this plugin and have been reporting this exact issue. 

Last time i parsed through the source, i notice that the direct object responsible for calling the email transaction was not being used. This only occurred for the re-send feature.

**Comment by aschroder** [comment] 2015-02-26 21:14
Are we talking about this action?

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php#L135

public function emailAction()

Which in 1.9.1 will add the email to the queue:

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Sales/Model/Order.php#L1356


In 1.9 it'd send immediately:

https://github.com/OpenMage/magento-mirror/blob/a1aca13823b7d10724d01b7597827c8bf024d270/app/code/core/Mage/Sales/Model/Order.php#L1262


Is the issue that it does not resend the email when you click the 'send
email' button? Does core magento without SMTP Pro?

**Comment by innoc** [comment] 2015-10-14 17:29
@aschroder  I just installed the SMTP plugin and I have observed a very strange behaviour. The problem is that I can only send emails to one email address (The email address I used in authenticating). 

These are my configuration settings

Email Connection:    Custom SMTP
Authentication:         Login
Username:               xxxxxxxxx@gmail.com
Password:                *******
Host:                        smtp.gmail.com
Port:                         465
SSL Security:           SSL

When testing my reset password functionality, I was only able to send emails the email address specified in the username field.

**Comment by aschroder** [comment] 2015-10-14 17:48
Are the emails definitely going out via SMTP pro? Check the debug logs to
be sure.

**Comment by innoc** [comment] 2015-10-14 18:19
I have a limited knowledge in Magento but based on the Admin Actions log and SMTPPro email log, I can see some logged data that indicates that emails are leaving through SMTPPro. 

My confusion is that why does it only work on one email Address??

**Comment by innoc** [comment] 2015-10-14 18:24
I am currently using Magento v 1.11.1.0 . @aschroder could this be the problem?

**Comment by Riz0** [comment] 2015-10-20 19:58
@aschroder This is not a problem with SMTP Pro, it has been found in previous versions of Magento as well.

As described from the following link, "Magento checks to see if the order email has already been sent or not and if it has, it returns out of the function without any error, thus pretending everything worked out." : https://magento.stackexchange.com/questions/24396/magento-send-email-button-on-order-not-working

Now that Magento uses the email queue, that fix of commenting out the "return $this" doesn't work. 

I've even tried to change the "$mailer->setQueue($emailQueue)->send(); " to  "$mailer->send(); " to evade the queue all together like previous versions, but still doesn't work.

You have more collective knowledge of Magento email then most, do think it's possible to fix this by changing a few lines in "app/code/core/Mage/Sales/Model/Order.php" ?

**Comment by rajsaha6** [comment] 2015-11-06 10:46
@aschroder I am using Custom SMtp with your extension. It's Working fine for all email but I need a copy  of all sales emails as admin and then no sales emails are working. I have checked the log file for sales emails.

2015-11-06T10:43:43+00:00 DEBUG (7): Email not sent immediately, queued for sending.
2015-11-06T10:43:43+00:00 DEBUG (7): Email not sent immediately, queued for sending.

Is not it working for sales(order) emails? 

Please help

**Comment by tob47** [comment] 2016-06-20 06:32
why 127.0.0.1/magento/admin error "The 127.0.0.1 page isn’t working"  after install ASchroder_SMTPPro, in magento v 1.9.2

**Comment by tob47** [comment] 2016-06-21 06:59
work thangks

**Comment by hzubyrss** [comment] 2017-02-02 15:15
Email not sent in most of the case because cron job do not work well on your server so i would recommend you to first of all contact your hosting provider and ask them for help good web hosting provider always help in creating cron since its not big job if your hosting is not good you may look on this [magento optimized hosting provider](https://goo.gl/8lkwJl) ,  or follow the steps here [how to create cron on cpanel ](https://goo.gl/vLWuKh)

**Comment by sandermangel** [comment] 2018-03-10 21:24
@bank32  this issue has been open for quite some time. I will go ahead and close it. If the issue persists for you or you have any more information please open the ticket again.

**Closed by sandermangel** 2018-03-10 21:24 UTC
