### ISSUE TITLE
Exception message was: Incorrect authentication data

### ISSUE THREAD

**Issue by ghost** [aschroder/Magento-SMTP-Pro-Email-Extension#167] opened 2016-05-10 18:59 UTC
No matter what I keep getting the same error when trying to set this up:

> SMTP Pro Self Test Results
> Sending test email to your contact form address: [removed] from: [removed]. Unable to send test email.
> Exception message was: Incorrect authentication data
> Please check the user guide for frequent error messages and their solutions.
> Default templates exist.
> Email communications are enabled.
> 
> Testing failed, please review the reported problems and if you need further help visit the support page or contact me via support@aschroder.com for support.

I've tried Custom SMTP (smtp.outlook.office365.com or smtp.office365.com, Login with credentials on port 25, or 587 Plain, SSL, or SSL TLS) and I've tried Gmail, but they both result in the same error message when running the self test. If I run any email from within Magento (Invoice, Shipment, New Order, etc) they are not sent.

Please advise on how to move forward with being able to use your extension.

Magento 1.9.2.3

Thanks

**Comment by aschroder** [comment] 2016-05-10 20:46
Sometimes this is caused by the web hosting or server security settings -
try testing with 1-2 other SMTP services (just a free trial account would
be fine with e.g SendGrid) if you get the same error then check with your
server admin or web hosting support to check if they are blocking outbound
SMTP or somehow interfering with it.

**Comment by Xaltus** [comment] 2016-05-10 21:10
I signed up for SendGrid and MailUp, and get the same error message with those as well. When I disable SMTPPro, emails are sent out but only to certain customers. Most customers complain they never received any email. So I was recommended to try your SMTP Pro extension to address this problem, but having no luck to get it to work. What do you propose as a fix for this could be?

**Comment by aschroder** [comment] 2016-05-10 21:16
this sounds like a web hosting issue to me - when the connection is failing
to more than 1 SMTP service provider, it's probably your own server
security settings that are interfering. Check with your server admin or web
host support if they allow/block/change outbound SMTP connections or how
they suggest doing them.

or, use MageSend - I pretty much designed it exactly because of this sort
of crap - it uses outbound HTTP calls for sending, rather than SMTP
protocol - so it bypasses 99.9% o the weird shit that hosts do to try and
block spammers.

**Comment by Xaltus** [comment] 2016-05-10 21:20
Ok thank you very much for the assistance, we will contact our server admin to to see what's going on. If all else fails, we'll give MageSend a shot, it sounds promising. 

Thanks!

**Comment by Xaltus** [comment] 2016-05-12 15:28
This case can be closed. It was a server configuration, just like you said. Thanks for pointing me in the right direction!

Top notch extension, buddy.

**Closed** 2019-04-04 10:39 UTC
