### ISSUE TITLE
Modman file error (wrong path)

### ISSUE THREAD

**Issue by clojens** [aschroder/Magento-SMTP-Pro-Email-Extension#50] opened 2014-08-11 09:25 UTC
Modman file contains a reference to what ends up locally at `../vendor/aschroder/smtp_pro/**code**/app/..`. The `code` part of the path is not reflected in the actual file hierarchy in the project hence it fails to initially detect the module xml file in app/etc. Creating either `code` as a folder and moving `app` inside or modifying the `modman` file resolves this issue.

**Comment by ntejapermana** [comment] 2015-03-05 06:14
+1

The extension can't be installed via Composer without this fix.

**Comment by ihor-sviziev** [comment] 2015-03-05 06:47
@ntejapermana and @clojens what do you mean? I have installed this module via composer without any issues.

**Comment by animalinteractive** [comment] 2015-03-05 07:05
To those having issues, install against dev-master.

**Comment by dimasdwika** [comment] 2015-03-06 00:43
It seems this issue happening on version 2.0.0. I think is because on tag release 2.0.0, modman file still referencing /code folder and the actual file itself don't have /code folder which is straight to /app

**Comment by ntejapermana** [comment] 2015-03-06 10:57
Like @dimasdwika said, the problem is on version 2.0.0. I've found out later that the latest version is 2.0.5. But, since there is no tag for that version, the composer still pull the version 2.0.0 even if you use "*". 
Thanks @animalinteractive, install against dev-master resolve the issue.

**Comment by clojens** [comment] 2015-03-26 15:18
Right. I would still urge to do proper (git-flow is my favorite) versioned releases and refrain from doing `dev-master` publishing too much. Especially if anyone other than developers are supposed to use it (and to me, this is the case when using composer but I guess some would use it for development as well although I don't see the use of it). The whole `dev-master` use in the community is really nasty. It easily breaks solutions way too easily, please [read this article](https://igor.io/2013/01/07/composer-versioning.html) to see why, if you have no idea what I'm talking about.

**Comment by sandermangel** [comment] 2018-03-10 21:35
The fix has been released in 2.0.5

**Closed by sandermangel** 2018-03-10 21:35 UTC
